version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        - UID=${UID}
    image: happy-backend
    command: sh .docker/scripts/run.sh
    volumes:
      - ../:/home/node/app
    ports:
      - 3000:3000
