version: '3'

services:
  app:
    build:
      context: .
      args:
        UID: $UID
    container_name: app
    image: app
    command: ./.docker/entrypoint.sh
    volumes:
      - static-data:/vol/web
      - .:/home/python/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static-data:


